_base_: '../_base_/rice_voc12.yml'

model:
  type: DeepLabV3P
  backbone:
    type: SwinTransformer

    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz

  backbone_indices: [0, 3]
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null
